apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: e2b11cflr-nodejs 
  janus-idp.io/tekton: e2b11cflr-nodejs
  backstage.io/kubernetes-id: e2b11cflr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e2b11cflr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml